### ISSUE TITLE
Metadata: publish under TrIAS or not?

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/uredinales-belgium-checklist#10]
I'm currently writing the metadata for the rust fungi. For this, it would be good to define the scope of the publication, i.e. do we publish it as a part of TrIAS or not? Or: do I mention the following:

> This dataset was published as open data for the TrIAS project (Tracking Invasive Alien Species http://trias-project.be, Vanderhoeven et al. 2017), with technical support provided by the Research Institute for Nature and Forest (INBO). It is selected as one of the authoritative sources for the compilation of a unified and standardized checklist of alien species in Belgium.

**Comment by qgroom** [comment]
Yes, we certainly would not have done it were it not for TrIAS.
Your attribution seems appropriate.

**Comment by timadriaens** [comment]
agree
