### ISSUE TITLE
Should we keep static values in raw data?

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/uredinales-belgium-checklist#4]
The following fields in the raw data file have the same value for all records. I would just add this static information **once** via the Rmd script and remove these from the raw data. @qgroom is that OK?

* [x] nomenclaturalCode: `ICBN`
* [x] license: `http://creativecommons.org/publicdomain/zero/1.0/legalcode` (suggest to use `http://creativecommons.org/publicdomain/zero/1.0/` instead)
* [x] bibliographicCitation: 3 verbose values, would add based on `part`
* [x] countryCode: `BE`
* [x] country: `Belgium`
* [x] institutionID: `http://biocol.org/urn:lsid:biocol.org:col:15605` (see also #3)
* [x] institutionCode: `institutionCode`
* [x] datasetName: `Catalogue des Uredinales de Belgique`

In addition, `eventDate` and to lesser extent `taxonRank` could probably generated ...

**Comment by qgroom** [comment]
Only bibliographicCitation varies. I have the page number in the file for every treatment which could be used with the bibliographicCitation to specify the exact location. It is not entirely necessary though.

**Comment by LienReyserhove** [comment]
@qgroom I now removed all DwC terms listed by @peterdesmet from the raw data file.

For `bibliographicCitation`, I kept `part` (volume number) and `page` in the raw file, and I removed the original column `bibliograhicCitation` (full reference).  In the .Rmd file, I complement this information by linking `part` with the full reference based on this table:

|part |full_reference                                                                                                                                                                                                                                          |
|:--------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|1        |Vanderweyen, A., & Fraiture, A. (2009). Catalogue des Uredinales de Belgique, 1re partie, Chaconiaceae, Coleosporiaceae, Cronartiaceae, Melampsoraceae, Phragmidiaceae, Pucciniastraceae, Raveneliaceae et Uropyxidaceae. Lejeunia, Revue de Botanique. |
|2        |Vanderweyen, A., & Fraiture, A. (2009). Catalogue des Uredinales de Belgique, 2ème partie, Pucciniaceae (sauf Puccinia)(suite 2). Lejeunia, Revue de Botanique.                                                                                         |
|3        |Vanderweyen, A., & Fraiture, A. (2012). Catalogue des Uredinales de Belgique, 3ème partie, Pucciniaceae (genre Puccinia). Lejeunia, Revue de Botanique.                                                                                                 |

So, in the raw file, only the volume and page number is given, while in the mapping, the full reference and page number is given.

Is that ok for you? If this sound a bit complex, I can explain you on Monday.

**Comment by qgroom** [comment]
That sounds fine
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be
