### ISSUE TITLE
Some decisions needed

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/uredinales-belgium-checklist#7]
I'm currently mapping the data to DwC Archive, but some questions arise. @qgroom can you help me with this?

1. Which data will we use eventually? Now, the checklist is a mixture of alien and native species (in the field `Column`). In case of alien, I suppose this means "an alien rust fungus on a native plant", in case of native, this is "a native rust fungus on an alien plant". Or am I wrong? Anyway, I would only include alien rust fungi.

2. What exactly do you mean with `catalogueNumber`? Is this the same as `taxonID`, specifically generated for this checklist? Now, it's the same as the row number of the species.

3. nomenclaturalCode = ICBN?

4. What does the information in `part` and `number` describe exactly? 
e.g.: part = 3 *(Vanderweyen, A., & Fraiture, A. (2012). Catalogue des Uredinales de Belgique, 3ème partie, Pucciniaceae (genre Puccinia). Lejeunia, Revue de Botanique)*,  Page: 16. Is this the full description of the species? Or rather just a small paragraph discussing its distribution? or...

**Comment by peterdesmet** [comment]
On 1. we indeed to know how the species are alien, but I would publish both alien and non alien species in this checklist. It’s the scope of the dataset and we can easily differentiate between the two.

Also, are the host plants included in the data?

**Comment by qgroom** [comment]
1. The publication does specify when some species are alien, but there are others not mentioned as alien, but are found on alien plants, so presumably alien. It depends on if you consider crops like wheat alien.

2. The `catalogueNumber` is the number give to that taxon in the publication. It is described in the Darwin Core documentation as "An identifier (preferably unique) for the record within the data set or collection". This sounds about right.

3. Yes, stick with ICBN, though this should be looked at by someone. The latest code should be called the ICNAFP or just ICN. It really needs a controlled vocabulary, which includes the dates. Having said that I have no idea why we need nomenclaturalCode in observation data!

4. The Catalogue was published in three seperate parts, several species treatments were on each page and each treatment was numbered. There is little description of the species, most of the information is about taxonomy, observations and the hosts.

**Comment by peterdesmet** [comment]
1. We'll have to make a decision then on which ones we consider alien.
2. That fits the definition, but it is really used for specimens... which might be confusing here. In any case, it's not available for taxa. It's a [taxonID](http://rs.tdwg.org/dwc/terms/index.htm#taxonID). Since we'll create our own taxonID, we'll have to decide if and where we want to keep this original ID.

**Comment by qgroom** [comment]
1. just use the alien status that is in the far right of the table for now. I will try to review then soon, but there will be few new aliens.
2. I'm fine dropping `catalogueNumber` or putting it somewhere else.

You did find the `associateTaxa` column in the data for the host species?

**Comment by LienReyserhove** [comment]
So,

1. I'm keeping all species (alien and native) in the checklist. I will specify their status in `establishmentMeans`, as I did before for the other checklists:

raw_data | establishmentMeans
--- | ---
native | native
alien | introduced
NA | NA

Later, we can still decided which species to integrate in the unified checklist...

2. In my opinion, I would drop `catalogueNumber`. You could perhaps integrate it in the [Types and Specimens Extension](http://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml), but that extension would not add a lot of information to the checklist (`bibliographicCitation` is already in the Taxon Core). 

3. I stick with ICBN

4.  I will integrate `part` and `number` under `bibliographicCitation` in the Taxon Core, as this appears to be the most appropriate to me. 

5. and yes, `associatedTaxa` is in the raw data. @peterdesmet : perhaps something for the [Resource Relationship Extension](http://rs.gbif.org/extension/dwc/resource_relation.xml)?

**Comment by peterdesmet** [comment]
- Agree on 1-3
- Agree on 4, would also add this `source` in any of the extensions, so best to make it part of pre-processing (cf. alien-macroinv)
- Regarding `associatedTaxa`: yes, http://rs.gbif.org/extension/dwc/resource_relation_2018_01_18.xml (updated version!) would be the best, but it does mean that every host plant should have its own record in the taxon core. Do we have enough information on those to create those records?

**Comment by peterdesmet** [comment]
Creating separate issue for associated taxa #8

**Comment by qgroom** [comment]
I agree with 1-4 and creating a new issue on associatedTaxa. I am keen to capture the host information. Among other reasons it is highly relevant to species impacts.
